version: '{build}'
skip_non_tags: true
image: Visual Studio 2017
environment:
  npm_token:
    secure: zzCasUeeWgFawE+gkXpzEpbXojeFn7ii92FPywONNNRPMGA8n1wF7p9YJoMm1t2Y
install:
- ps: Install-Product node 8.9.1 x64
- cmd: if not exist "./node_modules" yarn install
build_script:
- ps: |
    yarn run build-dist
    new-item .npmrc -type file
    add-content .npmrc "//registry.npmjs.org/:_authToken=$($env:npm_token)"
    yarn publish --no-git-tag-version --new-version $env:APPVEYOR_REPO_TAG_NAME
# If caching fails, the entire build fails - https://github.com/appveyor/ci/issues/1509
#cache:
#    - node_modules -> package.json
test: off