version: '{build}'
on:
  appveyor_repo_tag: true
image: Visual Studio 2017
environment:
  npm_token:
    secure: 6EuYnTHhFGD0uTKWxNy17MiH1oANxoFqKjbC+LaExoPJha6g9K337TiZ5rvXrBuW
install:
- cmd: if not exist "./node_modules" yarn install --pure-lockfile --ignore-optional
- ps: Install-Product node 8.9.1 x64
build_script:
- ps: |
    yarn run build-production
    new-item .npmrc -type file
    add-content .npmrc "//registry.npmjs.org/:_authToken=$($env:npm_token)"
    npm version $env:APPVEYOR_REPO_TAG_NAME
    npm publish
cache:
    - node_modules -> package.json
test: off