trigger:
- master

resources:
  repositories:
  - repository: templates
    type: github
    name: JeringTech/DevOps.AzurePipelines
    endpoint: JeremyTCD

jobs:
- template: templates/npm/main.yml@templates
  parameters:
    npmUnreleasedPrereleasePublishEndpoint: "https://www.myget.org/F/jering/npm/" 