trigger:
- master

resources:
  repositories:
  - repository: templates
    type: github
    name: JeremyTCD/DevOps.AzurePipelines
    endpoint: JeremyTCD

jobs:
- template: templates/npm/main.yml@templates
  parameters:
    installRegistryEndpoint: "https://pkgs.dev.azure.com/JeremyTCD/_packaging/Main/npm/registry/"
    publishRegistryEndpoint: "https://pkgs.dev.azure.com/JeremyTCD/_packaging/Main/npm/registry/"